name: starknet_builder
description: The Dart SDK builder for contracts on starknet
version: 0.0.4
repository: https://github.com/gabsn/starknet.dart

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  build: ^2.3.1
  code_builder: ^4.4.0
  dart_style: ^2.2.4
  path: ^1.8.3
  starknet:

dev_dependencies:
  analyzer: ^5.4.0
  build_runner: ^2.1.11
  build_test: ^2.1.6
  lints: ^2.0.0
  test: ^1.16.0
