name: secure_store
description: Zero-config wallet components for starknet
version: 0.1.2
homepage: https://github.com/gabsn/starknet.dart/tree/main/packages/secure_store

environment:
  sdk: ">=2.17.3 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  pointycastle: ^3.7.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  pigeon: ^21.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.secure_store
        pluginClass: SecureStorePlugin
      ios:
        pluginClass: SecureStorePlugin
      macos:
        pluginClass: SecureStorePlugin
