name: starknet
description: The Dart SDK to interact with any smart contracts on StarkNet
version: 0.0.4
repository: https://github.com/gabsn/starknet.dart

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  crypto: ^3.0.2
  freezed_annotation: ^2.0.3
  http: ^1.0.0
  json_annotation: ^4.5.0
  pointycastle: ^3.6.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.16.0
