name: starknet_flutter
description: Zero-config wallet components for starknet
version: 0.1.2
homepage: https://github.com/gabsn/starknet.dart/tree/main/packages/starknet_flutter

environment:
  sdk: ">=2.17.3 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  bip39: ^1.0.6
  crypto: ^3.0.2
  expandable: ^5.0.1
  flutter_svg: ^2.0.2
  intl: ^0.18.0
  functional_listener: ^2.3.1
  google_fonts: ^5.0.0
  loading_indicator: ^3.1.0
  confetti: ^0.7.0
  hive: ^2.2.3
  flutter_animate: ^4.1.0
  hive_flutter: ^1.1.0
  http: ^1.0.0
  modal_bottom_sheet: ^3.0.0-pre
  path_provider: ^2.0.13
  pattern_lock: ^2.0.0
  slide_to_act_reborn: ^3.0.0
  plugin_platform_interface: ^2.0.2
  pointycastle: ^3.6.2
  starknet:
  ulid: ^2.0.0
  mobile_scanner: ^3.0.0
  qr_flutter: ^4.1.0
  riverpod: ^2.3.6
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  pigeon: ^10.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.starknet_flutter
        pluginClass: StarknetFlutterPlugin
      ios:
        pluginClass: StarknetFlutterPlugin
      macos:
        pluginClass: StarknetFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/wallets/argent.svg
    - assets/images/wallets/braavos.svg
    - assets/images/wallets/openZeppelin.svg
    - assets/images/logo.svg
    - assets/images/crypto/eth.svg
    - assets/images/qr_code_placeholder.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
