name: starknet_cli
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  starknet:
  starknet_provider:
  args: ^2.4.2
  csv: ^5.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
