name: wallet_kit
description: A UI toolkit that simplifies blockchain wallet integration in Flutter apps.
version: 0.2.0
homepage: "https://starknetdart.dev"

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  ark_project: ^0.3.0
  starknet: ^0.1.2+1
  starknet_provider: ^0.1.1+2
  secure_store: ^0.1.2+1
  bip39: ^1.0.6
  easy_debounce: ^2.0.3
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hooks_riverpod: ^2.3.6
  image_network: ^2.5.4+1
  riverpod_annotation: ^2.1.1
  uuid: ^4.0.0
  go_router: ^14.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint_builder: ^0.6.4
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  meta: ^1.11.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  freezed: ^2.3.5
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/crypto/
    - assets/images/wallets/

  fonts:
    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Black.otf
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Rounded-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Rounded-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Rounded-Ultralight.otf
          weight: 100
