name: starknet_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

dependencies:
  starknet:
  freezed_annotation: ^2.0.3
  http: ^1.0.0
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lints: ^4.0.0
  test: ^1.16.0
